# Generated by Django 5.2 on 2025-12-09 04:01

import khatma.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khatma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deceased',
            options={'ordering': ['-created_at'], 'verbose_name': 'المتوفى', 'verbose_name_plural': 'المتوفين'},
        ),
        migrations.AddField(
            model_name='deceased',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='death_date',
            field=models.DateField(db_index=True, verbose_name='تاريخ الوفاة'),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='اسم المتوفى'),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='photo',
            field=models.ImageField(blank=True, help_text='Maximum file size: 2MB. Allowed formats: JPG, JPEG, PNG, GIF.', null=True, upload_to='deceased_photos/%Y/%m/%d/', validators=[khatma.models.validate_image_file_extension], verbose_name='صورة المتوفى'),
        ),
        migrations.AlterField(
            model_name='khatma',
            name='title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='عنوان الختمة'),
        ),
        migrations.AlterUniqueTogether(
            name='deceased',
            unique_together={('name', 'death_date', 'added_by')},
        ),
        migrations.AddIndex(
            model_name='deceased',
            index=models.Index(fields=['name'], name='deceased_name_idx'),
        ),
        migrations.AddIndex(
            model_name='deceased',
            index=models.Index(fields=['death_date'], name='deceased_death_date_idx'),
        ),
    ]
