# Generated by Django 4.2.23 on 2025-07-12 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
                ('verification_token', models.UUIDField(default=users.models.get_default_token_expiry, editable=False, verbose_name='Verification Token')),
                ('verification_token_expires', models.DateTimeField(default=users.models.get_default_token_expiry, verbose_name='Verification Token Expires')),
                ('password_reset_token', models.UUIDField(blank=True, null=True, editable=False, verbose_name='Password Reset Token')),
                ('password_reset_token_expires', models.DateTimeField(blank=True, null=True, verbose_name='Password Reset Token Expires')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('last_failed_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Failed Login')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Locked Until')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('last_login_user_agent', models.TextField(blank=True, null=True, verbose_name='Last Login User Agent')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Two-Factor Authentication Enabled')),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True, verbose_name='Two-Factor Secret')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Terms Accepted')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Marketing Consent')),
                ('data_processing_consent', models.BooleanField(default=False, verbose_name='Data Processing Consent')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Last Activity')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_khatma', 'أول ختمة'), ('memorial_khatma', 'ختمة تذكارية'), ('full_quran', 'ختمة كاملة'), ('ramadan_khatma', 'ختمة رمضان'), ('community_khatma', 'ختمة مجتمعية')], max_length=30)),
                ('points_earned', models.IntegerField(default=0)),
                ('achieved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('individual', 'حساب فردي'), ('family', 'حساب عائلي'), ('charity', 'مؤسسة خيرية'), ('mosque', 'مسجد'), ('school', 'مدرسة'), ('organization', 'مؤسسة')], default='individual', max_length=20, verbose_name='نوع الحساب')),
                ('total_points', models.IntegerField(default=0, verbose_name='مجموع النقاط')),
                ('level', models.IntegerField(default=1, verbose_name='المستوى')),
                ('consecutive_days', models.IntegerField(default=0, verbose_name='أيام متتالية')),
                ('last_activity_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ آخر نشاط')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10, verbose_name='اللغة المفضلة')),
                ('reading_preference', models.CharField(choices=[('uthmani', 'الرسم العثماني'), ('simple', 'الرسم الإملائي البسيط'), ('tajweed', 'مع علامات التجويد')], default='uthmani', max_length=20, verbose_name='تفضيل القراءة')),
                ('font_size', models.IntegerField(default=18, verbose_name='حجم الخط')),
                ('night_mode', models.BooleanField(default=False, verbose_name='الوضع الليلي')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='الصورة الشخصية')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة شخصية')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='الموقع')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('family_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم العائلة')),
                ('family_admin', models.BooleanField(default=False, verbose_name='مدير العائلة')),
                ('organization_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المؤسسة')),
                ('organization_website', models.URLField(blank=True, null=True, verbose_name='موقع المؤسسة')),
                ('organization_logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/', verbose_name='شعار المؤسسة')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='إشعارات الدفع')),
                ('family_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='users.profile', verbose_name='مجموعة العائلة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
