# Generated by Django 4.2.23 on 2025-07-18 10:33

from django.db import migrations, models
import django.utils.timezone


def set_default_created_at(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    # Set a default created_at for existing profiles
    Profile.objects.all().update(created_at=django.utils.timezone.now())

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='default_quran_reciter',
            field=models.CharField(blank=True, help_text="User's default Quran reciter", max_length=100, verbose_name='default Quran reciter'),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, help_text="User's full name", max_length=255, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_email',
            field=models.BooleanField(default=False, help_text='Whether to show email to other users', verbose_name='show email'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_khatmas_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='total khatmas completed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.RunPython(set_default_created_at, migrations.RunPython.noop),
    ]
