# Generated by Django 5.2 on 2025-12-09 03:27

from django.db import migrations, models
import datetime


def set_default_last_activity_date(apps, schema_editor):
    Profile = apps.get_model('users', 'Profile')
    # Update all profiles where last_activity_date is NULL
    Profile.objects.filter(last_activity_date__isnull=True).update(
        last_activity_date=datetime.date.today()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_profile_fields'),
    ]

    operations = [
        # First, make the field nullable in the database if it's not already
        migrations.AlterField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(
                null=True,
                blank=True,
                help_text='Date of last recorded activity',
                verbose_name='last activity date'
            ),
        ),
        # Run the data migration to set default values
        migrations.RunPython(set_default_last_activity_date, migrations.RunPython.noop),
        # Make the field non-nullable with a default value
        migrations.AlterField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(
                default=datetime.date.today,
                help_text='Date of last recorded activity',
                verbose_name='last activity date'
            ),
        ),
    ]
