# Generated by Django 5.2 on 2025-12-09 03:30

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_fix_last_activity_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user profile', 'verbose_name_plural': 'user profiles'},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-unlocked_at', '-created_at'], 'verbose_name': 'user achievement', 'verbose_name_plural': 'user achievements'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='family_admin',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='family_group',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the achievement was first created', verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userachievement',
            name='is_unlocked',
            field=models.BooleanField(default=False, help_text='Whether the achievement has been unlocked', verbose_name='is unlocked'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, help_text='Progress percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progress'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], default='bronze', help_text='Achievement tier level', max_length=20, verbose_name='tier'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement_type', 'tier')},
        ),
        migrations.AddField(
            model_name='userachievement',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, help_text='When the achievement was unlocked', null=True, verbose_name='unlocked at'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the achievement was last updated', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('teacher', 'Teacher'), ('admin', 'Administrator')], default='standard', help_text='Type of user account', max_length=20, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='A short biography about the user', null=True, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text="User's date of birth", null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='consecutive_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive days with activity', verbose_name='consecutive days'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Enable email notifications', verbose_name='email notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_name',
            field=models.CharField(blank=True, help_text="User's family name", max_length=255, null=True, verbose_name='family name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='font_size',
            field=models.PositiveSmallIntegerField(default=16, help_text='Preferred font size for reading (8-72px)', validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(72)], verbose_name='font size'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Date of last recorded activity', null=True, verbose_name='last activity date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.PositiveIntegerField(default=1, help_text='User level based on activity', verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, help_text="User's location", max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='night_mode',
            field=models.BooleanField(default=False, help_text='Enable dark mode/night theme', verbose_name='night mode'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization_logo',
            field=models.ImageField(blank=True, help_text="Logo of the user's organization", null=True, upload_to='organization_logos/', verbose_name='organization logo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, help_text="Name of the user's organization", max_length=255, null=True, verbose_name='organization name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization_website',
            field=models.URLField(blank=True, help_text="Website of the user's organization", max_length=255, null=True, verbose_name='organization website'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ar-dz', 'Algerian Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('ckb', 'Central Kurdish (Sorani)'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('ig', 'Igbo'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('ky', 'Kyrgyz'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('ms', 'Malay'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('tg', 'Tajik'), ('th', 'Thai'), ('tk', 'Turkmen'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('ug', 'Uyghur'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('uz', 'Uzbek'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='ar', help_text="User's preferred language", max_length=10, verbose_name='preferred language'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="User's profile picture", null=True, upload_to='profile_pics/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='push_notifications',
            field=models.BooleanField(default=True, help_text='Enable push notifications', verbose_name='push notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reading_preference',
            field=models.CharField(choices=[('standard', 'Standard'), ('uthmani', 'Uthmani'), ('indopak', 'Indo-Pak')], default='standard', help_text='Preferred Quran reading style', max_length=20, verbose_name='reading preference'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_points',
            field=models.PositiveIntegerField(default=0, help_text='Total points earned by the user', verbose_name='total points'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement_type',
            field=models.CharField(choices=[('khatma_completion', 'Khatma Completion'), ('reading_streak', 'Reading Streak'), ('pages_read', 'Pages Read'), ('daily_goal', 'Daily Goal'), ('weekly_goal', 'Weekly Goal'), ('monthly_goal', 'Monthly Goal'), ('yearly_goal', 'Yearly Goal'), ('first_khatma', 'First Khatma'), ('fast_reader', 'Fast Reader'), ('consistent_reader', 'Consistent Reader')], help_text='Type of achievement', max_length=50, verbose_name='achievement type'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for this achievement', verbose_name='points earned'),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(help_text='The user who earned this achievement', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('email_verified', models.BooleanField(default=False, help_text='Designates whether the user has verified their email address.', verbose_name='Email Verified')),
                ('verification_token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Verification Token')),
                ('verification_token_expires', models.DateTimeField(default=datetime.datetime(2025, 12, 10, 3, 30, 13, 78260, tzinfo=datetime.timezone.utc), verbose_name='Verification Token Expires')),
                ('password_reset_token', models.UUIDField(blank=True, editable=False, null=True, verbose_name='Password Reset Token')),
                ('password_reset_token_expires', models.DateTimeField(blank=True, null=True, verbose_name='Password Reset Token Expires')),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, verbose_name='Failed Login Attempts')),
                ('last_failed_login', models.DateTimeField(blank=True, null=True, verbose_name='Last Failed Login')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Locked Until')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('last_login_user_agent', models.TextField(blank=True, null=True, verbose_name='Last Login User Agent')),
                ('two_factor_enabled', models.BooleanField(default=False, verbose_name='Two-Factor Authentication Enabled')),
                ('two_factor_secret', models.CharField(blank=True, max_length=32, null=True, verbose_name='Two-Factor Secret')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Terms Accepted')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Marketing Consent')),
                ('data_processing_consent', models.BooleanField(default=False, verbose_name='Data Processing Consent')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Last Activity')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_set', related_query_name='customuser', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_set', related_query_name='customuser', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='achieved_at',
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('profile_update', 'Profile Update'), ('khatma_start', 'Started a Khatma'), ('khatma_complete', 'Completed a Khatma')], max_length=50, verbose_name='activity type')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('device_id', models.CharField(blank=True, help_text='Unique identifier for the device', max_length=255, verbose_name='device ID')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional context about the activity', verbose_name='details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user activity',
                'verbose_name_plural': 'user activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'activity_type'], name='users_usera_user_id_421934_idx'), models.Index(fields=['created_at'], name='users_usera_created_828ca1_idx'), models.Index(fields=['ip_address'], name='users_usera_ip_addr_20d9f6_idx')],
            },
        ),
    ]
