# Generated by Django 5.2 on 2025-12-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_family_admin_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_admin',
            field=models.BooleanField(
                default=False,
                help_text='Designates whether the user is a family admin',
                verbose_name='family admin'
            ),
        ),
    ]
