# Generated by Django 5.2 on 2025-12-09 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_make_family_admin_not_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 10, 3, 52, 3, 446382, tzinfo=datetime.timezone.utc), verbose_name='Verification Token Expires'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='family_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a family admin', verbose_name='family admin'),
        ),
    ]
