# Generated by Django 5.2 on 2025-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_khatma_options_khatma_khatma_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatma',
            name='occasion_details',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='تفاصيل المناسبة'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='النقاط الإجمالية'),
        ),
        migrations.AlterField(
            model_name='khatma',
            name='frequency',
            field=models.CharField(choices=[('once', 'مرة واحدة'), ('weekly', 'أسبوعية'), ('monthly', 'شهرية'), ('ramadan', 'رمضان'), ('friday_nights', 'ليالي الجمعة')], default='once', max_length=20),
        ),
        migrations.AlterField(
            model_name='khatma',
            name='khatma_type',
            field=models.CharField(choices=[('regular', 'ختمة عادية'), ('memorial', 'ختمة للمتوفى'), ('charity', 'ختمة خيرية'), ('birth', 'ختمة ميلاد'), ('occasion', 'ختمة لمناسبة')], default='regular', max_length=20, verbose_name='نوع الختمة'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('individual', 'حساب فردي'), ('family', 'عائلي'), ('charity', 'مؤسسة خيرية')], default='individual', max_length=20, verbose_name='نوع الحساب'),
        ),
    ]
