# Generated by Django 5.2 on 2025-05-01 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_khatma_occasion_details_profile_total_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khatma',
            name='occasion_details',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_points',
        ),
        migrations.AlterField(
            model_name='khatma',
            name='frequency',
            field=models.CharField(choices=[('once', 'مرة واحدة'), ('weekly', 'أسبوعية'), ('monthly', 'شهرية')], default='once', max_length=10),
        ),
        migrations.AlterField(
            model_name='khatma',
            name='khatma_type',
            field=models.CharField(choices=[('regular', 'ختمة عادية'), ('memorial', 'ختمة للمتوفى'), ('charity', 'ختمة خيرية'), ('ramadan', 'ختمة رمضان'), ('birth', 'ختمة مولد'), ('graduation', 'ختمة تخرج'), ('wedding', 'ختمة زفاف')], default='regular', max_length=20, verbose_name='نوع الختمة'),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'إعجاب'), ('pray', 'دعاء'), ('support', 'دعم')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('individual', 'حساب فردي'), ('family', 'حساب عائلي'), ('charity', 'مؤسسة خيرية')], default='individual', max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.CreateModel(
            name='KhatmaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('khatma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.khatma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'رسالة الدردشة',
                'verbose_name_plural': 'رسائل الدردشة',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('first_khatma', 'أول ختمة'), ('ramadan_khatma', 'ختمة رمضان'), ('consecutive_days', 'أيام متتالية'), ('full_quran', 'ختمة كاملة')], max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('khatma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.khatma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إنجاز',
                'verbose_name_plural': 'الإنجازات',
                'unique_together': {('user', 'achievement_type', 'khatma')},
            },
        ),
    ]
