# Generated by Django 5.2 on 2025-05-02 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_khatma_options_remove_khatma_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='khatmachat',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='khatma_chat_audio/'),
        ),
        migrations.AddField(
            model_name='khatmachat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='khatma_chat_images/'),
        ),
        migrations.AddField(
            model_name='khatmachat',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='khatmachat',
            name='message_type',
            field=models.CharField(choices=[('text', 'نص'), ('dua', 'دعاء'), ('progress', 'تقدم'), ('achievement', 'إنجاز')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='khatmachat',
            name='part_completed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.quranpart'),
        ),
        migrations.CreateModel(
            name='PublicKhatma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_memorial', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('deceased_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deceased')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_khatmas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KhatmaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('dua', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('public_khatma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.publickhatma')),
            ],
        ),
        migrations.CreateModel(
            name='KhatmaInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'إعجاب'), ('jazak_khair', 'جزاك الله خيرًا')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('public_khatma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.publickhatma')),
            ],
            options={
                'unique_together': {('public_khatma', 'user', 'interaction_type')},
            },
        ),
    ]
