# Generated by Django 5.2 on 2025-05-03 10:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_khatma_social_media_hashtags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khatmapost',
            name='khatma',
        ),
        migrations.RemoveField(
            model_name='khatmapost',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='khatmachat',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userachievement',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='khatmainteraction',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='khatma',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='khatma',
            name='social_media_hashtags',
        ),
        migrations.RemoveField(
            model_name='khatma',
            name='social_media_image',
        ),
        migrations.RemoveField(
            model_name='khatmachat',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='khatmachat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='khatmachat',
            name='image',
        ),
        migrations.RemoveField(
            model_name='khatmachat',
            name='is_pinned',
        ),
        migrations.RemoveField(
            model_name='khatmachat',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='khatmachat',
            name='part_completed',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='khatma',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='khatma',
            name='frequency',
            field=models.CharField(choices=[('once', 'مرة واحدة'), ('weekly', 'أسبوعية'), ('monthly', 'شهرية'), ('ramadan', 'رمضان'), ('friday', 'كل جمعة')], default='once', max_length=20),
        ),
        migrations.AddField(
            model_name='khatma',
            name='memorial_prayer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='khatma',
            name='participants',
            field=models.ManyToManyField(related_name='joined_khatmas', through='core.Participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='khatmachat',
            name='is_dua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='khatmachat',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='khatmainteraction',
            name='khatma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.khatma'),
        ),
        migrations.AddField(
            model_name='khatmainteraction',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('khatma_invite', 'دعوة ختمة'), ('khatma_progress', 'تقدم ختمة'), ('achievement', 'إنجاز'), ('part_assigned', 'تعيين جزء'), ('comment', 'تعليق'), ('reminder', 'تذكير'), ('milestone', 'معلم مهم')], default='khatma_invite', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_khatma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.khatma'),
        ),
        migrations.AddField(
            model_name='participant',
            name='parts_read',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achieved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='deceased',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='khatma',
            name='deceased',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.deceased'),
        ),
        migrations.AlterField(
            model_name='khatma',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='khatma',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='khatma',
            name='khatma_type',
            field=models.CharField(choices=[('regular', 'ختمة عادية'), ('memorial', 'ختمة للمتوفى'), ('charity', 'ختمة خيرية'), ('birth', 'ختمة مولد'), ('healing', 'ختمة شفاء')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='khatma',
            name='sharing_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='khatma',
            name='target_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='khatmainteraction',
            name='interaction_type',
            field=models.CharField(choices=[('pray', 'دعاء'), ('thanks', 'جزاك الله خيرًا'), ('comment', 'تعليق')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('like', 'إعجاب'), ('prayer', 'دعاء'), ('thanks', 'شكر')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('individual', 'حساب فردي'), ('family', 'حساب عائلي'), ('charity', 'مؤسسة خيرية')], default='individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='achievement_type',
            field=models.CharField(choices=[('first_khatma', 'أول ختمة'), ('memorial_khatma', 'ختمة تذكارية'), ('full_quran', 'ختمة كاملة'), ('ramadan_khatma', 'ختمة رمضان'), ('community_khatma', 'ختمة مجتمعية')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='KhatmaPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('khatma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.khatma')),
            ],
            options={
                'unique_together': {('khatma', 'part_number')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('khatma', 'ختمة'), ('community', 'مجتمع'), ('memorial', 'تذكاري')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('khatma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.khatma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='postreaction',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.post'),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('user', 'post')},
        ),
        migrations.CreateModel(
            name='QuranReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.IntegerField()),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ بعد'), ('in_progress', 'جاري القراءة'), ('completed', 'مكتمل'), ('skipped', 'تم تخطيه')], default='not_started', max_length=20)),
                ('recitation_method', models.CharField(choices=[('reading', 'قراءة'), ('listening', 'استماع'), ('memorization', 'حفظ'), ('tajweed', 'تجويد')], default='reading', max_length=20)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('reciter', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('khatma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_readings', to='core.khatma')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'قراءة قرآن',
                'verbose_name_plural': 'قراءات القرآن',
                'ordering': ['-created_at'],
                'unique_together': {('khatma', 'part_number', 'participant')},
            },
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.RemoveField(
            model_name='khatmainteraction',
            name='public_khatma',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='khatma',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='points',
        ),
        migrations.DeleteModel(
            name='KhatmaPost',
        ),
    ]
