# Generated by Django 5.2 on 2025-05-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_birth_date_to_deceased'),
        ('core', '0012_add_memorial_image'),
    ]

    operations = [
    ]
