# Generated by Django 5.2 on 2025-05-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge'),
        ('core', '0013_merge_20250504_2247'),
    ]

    operations = [
    ]
