# Generated by Django 5.2 on 2025-05-07 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_khatmapart_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='khatmachat',
            options={'ordering': ['-created_at'], 'verbose_name': 'رسالة دردشة الختمة', 'verbose_name_plural': 'رسائل دردشة الختمة'},
        ),
        migrations.RemoveField(
            model_name='khatmachat',
            name='parent_message',
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('message_type', models.CharField(choices=[('text', 'نص'), ('dua', 'دعاء'), ('announcement', 'إعلان'), ('question', 'سؤال'), ('answer', 'إجابة'), ('welcome', 'ترحيب')], default='text', max_length=20, verbose_name='نوع الرسالة')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبتة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_chat_images/', verbose_name='صورة')),
                ('audio', models.FileField(blank=True, null=True, upload_to='group_chat_audio/', verbose_name='تسجيل صوتي')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='core.readinggroup', verbose_name='المجموعة')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.groupchat', verbose_name='رد على')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رسالة دردشة',
                'verbose_name_plural': 'رسائل الدردشة',
                'ordering': ['created_at'],
            },
        ),
    ]
