# Generated by Django 5.2 on 2025-05-08 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20240601_0000'),
    ]

    operations = [
        # This is a fake migration that does nothing
        # The original migration was trying to remove fields that don't exist
    ]
