# Generated by Django 5.2 on 2025-05-09 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20250509_1318'),
    ]

    operations = [
    ]
