# Generated by Django 5.2 on 2025-05-09 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_ayah_unique_together_remove_ayah_quran_part_and_more'),
        ('core', '0024_merge_20250509_1327'),
    ]

    operations = [
    ]
