# Generated by Django 5.2 on 2025-05-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_merge_20250509_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاشتراك')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر إرسال')),
            ],
            options={
                'verbose_name': 'اشتراك النشرة البريدية',
                'verbose_name_plural': 'اشتراكات النشرة البريدية',
            },
        ),
        migrations.DeleteModel(
            name='NewQuranBookmark',
        ),
    ]
