# Generated by Django 5.2 on 2025-05-09 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('khatma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('system', 'System Message')], default='text', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_chat_images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='group_chat_audio/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_chat_messages', to='groups.readinggroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Chat Message',
                'verbose_name_plural': 'Group Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KhatmaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('system', 'System Message')], default='text', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='chat_audio/')),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('khatma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_chat_messages', to='khatma.khatma')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khatma_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khatma Chat Message',
                'verbose_name_plural': 'Khatma Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
