# Generated by Django 4.2.23 on 2025-07-12 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khatma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatmachat',
            name='khatma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_chat_messages', to='khatma.khatma'),
        ),
        migrations.AddField(
            model_name='khatmachat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khatma_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_chat_messages', to='groups.readinggroup'),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
