# Generated by Django 5.2 on 2025-05-08 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuranPart',
            fields=[
                ('part_number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='رقم الجزء')),
            ],
            options={
                'verbose_name': 'جزء قرآن',
                'verbose_name_plural': 'أجزاء قرآن',
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='QuranReciter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القارئ')),
                ('name_arabic', models.CharField(max_length=100, unique=True, verbose_name='اسم القارئ بالعربية')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة عن القارئ')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reciters/', verbose_name='صورة القارئ')),
                ('style', models.CharField(blank=True, max_length=100, null=True, verbose_name='نمط القراءة')),
            ],
            options={
                'verbose_name': 'قارئ',
                'verbose_name_plural': 'القراء',
            },
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah_number', models.IntegerField(unique=True)),
                ('name_arabic', models.CharField(max_length=255)),
                ('name_english', models.CharField(max_length=255)),
                ('revelation_type', models.CharField(choices=[('meccan', 'Meccan'), ('medinan', 'Medinan')], max_length=10)),
                ('verses_count', models.IntegerField()),
            ],
            options={
                'ordering': ['surah_number'],
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ayah_number_in_surah', models.IntegerField()),
                ('text_uthmani', models.TextField()),
                ('translation', models.TextField(blank=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('quran_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.quranpart')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayahs', to='quran.surah')),
            ],
            options={
                'verbose_name': 'آية',
                'verbose_name_plural': 'آيات',
                'ordering': ['surah', 'ayah_number_in_surah'],
                'unique_together': {('surah', 'ayah_number_in_surah')},
            },
        ),
        migrations.CreateModel(
            name='QuranReadingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_type', models.CharField(choices=[('uthmani', 'الخط العثماني'), ('naskh', 'خط النسخ'), ('hafs', 'خط حفص'), ('simple', 'خط بسيط')], default='uthmani', max_length=20, verbose_name='نوع الخط')),
                ('font_size', models.IntegerField(default=18, verbose_name='حجم الخط')),
                ('theme', models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن'), ('sepia', 'سيبيا'), ('green', 'أخضر فاتح')], default='light', max_length=20, verbose_name='المظهر')),
                ('show_translation', models.BooleanField(default=True, verbose_name='عرض الترجمة')),
                ('show_tajweed', models.BooleanField(default=True, verbose_name='عرض علامات التجويد')),
                ('preferred_reciter', models.CharField(blank=True, max_length=100, null=True, verbose_name='القارئ المفضل')),
                ('auto_play_audio', models.BooleanField(default=False, verbose_name='تشغيل الصوت تلقائياً')),
                ('last_read_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت آخر قراءة')),
                ('last_read_ayah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_read_by', to='quran.ayah', verbose_name='آخر آية مقروءة')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quran_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuranBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الإشارة المرجعية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='اللون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='quran.ayah')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quran_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إشارة مرجعية',
                'verbose_name_plural': 'إشارات مرجعية',
                'unique_together': {('user', 'ayah')},
            },
        ),
        migrations.CreateModel(
            name='QuranTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ur', 'Urdu'), ('id', 'Indonesian'), ('tr', 'Turkish'), ('ru', 'Russian'), ('fa', 'Persian')], max_length=10, verbose_name='اللغة')),
                ('translator', models.CharField(max_length=100, verbose_name='المترجم')),
                ('text', models.TextField(verbose_name='نص الترجمة')),
                ('ayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='quran.ayah', verbose_name='الآية')),
            ],
            options={
                'verbose_name': 'ترجمة',
                'verbose_name_plural': 'الترجمات',
                'unique_together': {('language', 'translator', 'ayah')},
            },
        ),
        migrations.CreateModel(
            name='QuranRecitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='recitations/', verbose_name='ملف الصوت')),
                ('bitrate', models.CharField(blank=True, max_length=20, null=True, verbose_name='معدل البت')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='المدة')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='حجم الملف')),
                ('start_ayah', models.IntegerField(blank=True, null=True, verbose_name='آية البداية')),
                ('end_ayah', models.IntegerField(blank=True, null=True, verbose_name='آية النهاية')),
                ('reciter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='quran.quranreciter', verbose_name='القارئ')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recitations', to='quran.surah', verbose_name='السورة')),
            ],
            options={
                'verbose_name': 'تلاوة',
                'verbose_name_plural': 'التلاوات',
                'unique_together': {('reciter', 'surah', 'start_ayah', 'end_ayah')},
            },
        ),
    ]
