# Generated by Django 5.2 on 2025-05-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surah',
            name='revelation_order',
            field=models.IntegerField(default=0),
        ),
    ]
