# Generated by Django 4.2.23 on 2025-07-12 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبت')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'عضو'), ('moderator', 'مشرف'), ('admin', 'مدير')], default='member', max_length=20, verbose_name='الدور')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم المجموعة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف المجموعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='group_images/', verbose_name='صورة المجموعة')),
                ('is_public', models.BooleanField(default=True, verbose_name='مجموعة عامة')),
                ('allow_join_requests', models.BooleanField(default=True, verbose_name='السماح بطلبات الانضمام')),
                ('max_members', models.IntegerField(default=0, verbose_name='الحد الأقصى للأعضاء (0 = غير محدود)')),
                ('enable_chat', models.BooleanField(default=True, verbose_name='تفعيل المحادثة')),
                ('enable_khatma_creation', models.BooleanField(default=True, verbose_name='السماح بإنشاء ختمات')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='منشئ المجموعة')),
                ('members', models.ManyToManyField(related_name='joined_groups', through='groups.GroupMembership', to=settings.AUTH_USER_MODEL, verbose_name='أعضاء المجموعة')),
            ],
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='رسالة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'تم الرفض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المعالجة')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.readinggroup', verbose_name='المجموعة')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='تمت المعالجة بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.readinggroup', verbose_name='المجموعة'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.CreateModel(
            name='GroupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('event_type', models.CharField(choices=[('meeting', 'اجتماع'), ('khatma_start', 'بدء ختمة'), ('khatma_completion', 'إكمال ختمة'), ('lecture', 'محاضرة'), ('other', 'أخرى')], default='meeting', max_length=20, verbose_name='نوع الحدث')),
                ('start_time', models.DateTimeField(verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(verbose_name='وقت الانتهاء')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='المكان')),
                ('is_online', models.BooleanField(default=False, verbose_name='عبر الإنترنت')),
                ('meeting_link', models.URLField(blank=True, null=True, verbose_name='رابط الاجتماع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='groups.readinggroup', verbose_name='المجموعة')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
