# Generated by Django 4.2.23 on 2025-07-12 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('khatma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupevent',
            name='related_khatma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='khatma.khatma', verbose_name='الختمة المرتبطة'),
        ),
        migrations.AddField(
            model_name='groupannouncement',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المنشئ'),
        ),
        migrations.AddField(
            model_name='groupannouncement',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='groups.readinggroup', verbose_name='المجموعة'),
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
    ]
