# Generated by Django 5.2 on 2025-05-08 14:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_initial'),
        ('khatma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('khatma_progress', 'تقدم الختمة'), ('khatma_completed', 'اكتمال الختمة'), ('part_assigned', 'تعيين جزء'), ('part_completed', 'إكمال جزء'), ('memorial_khatma', 'ختمة تذكارية'), ('new_group_member', 'عضو جديد في المجموعة'), ('group_member_left', 'مغادرة عضو للمجموعة'), ('join_request', 'طلب انضمام'), ('join_request_approved', 'قبول طلب انضمام'), ('join_request_rejected', 'رفض طلب انضمام'), ('role_changed', 'تغيير الدور'), ('removed_from_group', 'إزالة من المجموعة'), ('new_announcement', 'إعلان جديد'), ('new_event', 'حدث جديد'), ('system', 'إشعار النظام'), ('welcome', 'ترحيب'), ('achievement', 'إنجاز')], max_length=30, verbose_name='نوع الإشعار')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء')),
                ('action_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='رابط الإجراء')),
                ('related_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.readinggroup', verbose_name='المجموعة المرتبطة')),
                ('related_khatma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='khatma.khatma', verbose_name='الختمة المرتبطة')),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'إشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('khatma_progress', models.BooleanField(default=True, verbose_name='تقدم الختمة')),
                ('khatma_completed', models.BooleanField(default=True, verbose_name='اكتمال الختمة')),
                ('part_assigned', models.BooleanField(default=True, verbose_name='تعيين جزء')),
                ('part_completed', models.BooleanField(default=True, verbose_name='إكمال جزء')),
                ('memorial_khatma', models.BooleanField(default=True, verbose_name='ختمة تذكارية')),
                ('group_member_changes', models.BooleanField(default=True, verbose_name='تغييرات أعضاء المجموعة')),
                ('join_requests', models.BooleanField(default=True, verbose_name='طلبات الانضمام')),
                ('group_announcements', models.BooleanField(default=True, verbose_name='إعلانات المجموعة')),
                ('group_events', models.BooleanField(default=True, verbose_name='أحداث المجموعة')),
                ('system_notifications', models.BooleanField(default=True, verbose_name='إشعارات النظام')),
                ('achievements', models.BooleanField(default=True, verbose_name='الإنجازات')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='إشعارات البريد الإلكتروني')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='إشعارات الدفع')),
                ('in_app_notifications', models.BooleanField(default=True, verbose_name='إشعارات داخل التطبيق')),
                ('enable_quiet_hours', models.BooleanField(default=False, verbose_name='تفعيل ساعات الهدوء')),
                ('quiet_hours_start', models.TimeField(default='22:00', verbose_name='بداية ساعات الهدوء')),
                ('quiet_hours_end', models.TimeField(default='07:00', verbose_name='نهاية ساعات الهدوء')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعداد الإشعارات',
                'verbose_name_plural': 'إعدادات الإشعارات',
            },
        ),
    ]
